### ISSUE TITLE
Will not work on windows 10 surface pro 2

### ISSUE THREAD

**Issue by spriglet66** [nutti/Blender-Add-on-Manager#16]
It works on my main pc running windows 10 but when trying to use it to install the same addons on my laptop the addon manager is non responsive; the buttons on the top show a loading icon which is really confusing? 

Also the manager will not show any information; any installed addons, favourites or GitHub?

**Comment by nutti** [comment]
> It works on my main pc running windows 10 but when trying to use it to install the same addons on my laptop the addon manager is non responsive; the buttons on the top show a loading icon which is really confusing?

can you tell me the more detail, please?

* What add-on were you going to install?
* What version did you use?
* Was it a first time to use this application? Did you use more than two versions?
* Is there any error logs in ```C:\Users\<users>\AppData\Roaming\Blender_Add-on_Manager\logs```

**Comment by spriglet66** [comment]
<img width="765" alt="2018-02-20 5" src="https://user-images.githubusercontent.com/34583483/36439598-5ee8cb46-1665-11e8-9e71-8ebbb7885704.png">
I am trying to install whichever addons I want to use from the GitHub search- the search function shows no addons 
I am using version 2.79 of Blender
when I hover my cursor over the icons at the top the loading symbol shows up when hovering over everything inside the program which makes me think it doesn't have access to your database to update the addon list?

I have attached my app log.
I am trying to use your application on my two different computers so I can easily have the same addons installed on both my laptop and my desktop. The addon manager works fine on my desktop but when running the exact same program on my laptop (surface pro 2 Win 10) I expect to be able to search for the same addons that I already have installed on my desktop and install them on my laptop. However, the problem is that when trying to run the program on my laptop no addons are shown so I cannot search to install them?
[app.log](https://github.com/nutti/Blender-Add-on-Manager/files/1741231/app.log)
[lib.log](https://github.com/nutti/Blender-Add-on-Manager/files/1741232/lib.log)

Thank you.

**Comment by nutti** [comment]
Sorry for late response.

And thanks for your answering.
Is it possible to delete ```C:\Users\<users>\AppData\Roaming\Blender_Add-on_Manager\db``` ?

And I would like to know which version you use.
There are 5 releases now.
https://github.com/nutti/Blender-Add-on-Manager/releases

**Comment by nutti** [comment]
There is no response for a long time.
I will close it.
If you have any problem, please reopen it.
