### ISSUE TITLE
addon path that contain "." is not detected by Blender

### ISSUE THREAD

**Issue by ousttrue** [nutti/Blender-Add-on-Manager#8]
example(Windows10 + Blender2.78)

%USERPROFILE%\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\meshio(.pmd)@ousttrue

After I rename the path to "meshio(pmd)@ousttrue", Blender detect addon.

more example "S.T.A.L.K.E.R._Tools@Pavel_Blend"

**Comment by nutti** [comment]
thanks for your report.

AFAIK, it is similar bugs which i fixed on previous release (v0.3).
i will fix it until next release :-)

**Comment by nutti** [comment]
Sorry for my slow development.
I fixed this issue now.
